name: thesis
channels:
  - conda-forge
dependencies:
  # Core
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - ipykernel
  - tqdm

  # Optimization
  - pulp
  - pip:
      - gurobipy

  # Optional but recommended tools
  - pyyaml        # for experiment configs
  - pyarrow       # for parquet files
  - openpyxl      # read/write Excel
  - statsmodels   # regression / time series
  - plotly        # interactive plots
  - notebook      # classic notebook support

  # Testing & utilities
  - pytest
  - black
  - isort
  - pre-commit
